#!/usr/bin/env python3
"""
extract-dmaai-analysis.py — read a JDE DMAAI analyzer workbook
(`JDE DMAAIs Analysis {YYYY-MM-DD}.xlsx`) and emit the JSON sidecar
that powers `RRV8/accounting-dmaais.html`.

Output shape is defined in `docs/plans/dmaai-page-overlay-table.md` §4.

Usage:
    python3 extract-dmaai-analysis.py \
        --xlsx "<path to analyzer .xlsx>" \
        --out  "<path to dmaai-analysis-latest.json>"

If --out is omitted, writes to
`<repo>/RRV8/data/dmaai-analysis-latest.json` (resolved relative to
this script).

The owner can't run Python locally per policy; this script runs in
the agent's environment (or in CI). Commit the resulting JSON
alongside any script change.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from datetime import datetime
from pathlib import Path

try:
    import openpyxl
except ImportError:
    sys.stderr.write(
        "openpyxl is required. Install with:\n"
        "    python3 -m pip install --user openpyxl\n"
    )
    sys.exit(2)


# AAI-table -> module mapping. Strict spec listed only the analyzer's
# canonical tables per module; this map adds the related tables that
# show up in JDE Data on real installs so the module grids cover the
# whole F4095. AAIs not in any bucket land in `_meta.unmappedAais` so
# the analyst can spot drift.
MODULE_AAI = {
    "Sales":         {"4220", "4226", "4228", "4230", "4240", "4245", "4250",
                      "4270"},
    "Inventory":     {"4122", "4124", "4134", "4136", "4140", "4141", "4152",
                      "4154", "4162", "4164", "4172", "4174"},
    "Manufacturing": {"3110", "3120", "3130", "3210", "3220", "3240", "3260",
                      "3270", "3280", "3400", "3401"},
    "Purchasing":    {"4126", "4128", "4310", "4315", "4318", "4320", "4330",
                      "4332", "4335", "4337", "4340", "4350", "4355", "4365",
                      "4370", "4375", "4385", "4390", "4400", "4405"},
}


def _txt(v) -> str:
    return "" if v is None else str(v).strip()


def _parse_subline(s: str) -> dict:
    """`2,814 F4095 rows  ·  68 flagged across 3 patterns` -> dict."""
    out = {}
    m = re.search(r"([\d,]+)\s+F4095\s+rows", s)
    if m:
        out["totalRows"] = int(m.group(1).replace(",", ""))
    m = re.search(r"(\d+)\s+flagged", s)
    if m:
        out["flaggedCount"] = int(m.group(1))
    m = re.search(r"(\d+)\s+patterns?", s)
    if m:
        out["patternsCount"] = int(m.group(1))
    return out


def _parse_source_strip(s: str) -> dict:
    """`Source  JDE F4095 ...    May 22, 2026    Rows  2,814` -> dict."""
    # Strip is space-separated with big gaps; collapse to single spaces.
    flat = re.sub(r"\s{2,}", "\t", s).strip()
    parts = [p.strip() for p in flat.split("\t") if p.strip()]
    out = {}
    for i, p in enumerate(parts):
        low = p.lower()
        if low == "source" and i + 1 < len(parts):
            out["source"] = parts[i + 1]
        elif low == "rows" and i + 1 < len(parts):
            m = re.search(r"([\d,]+)", parts[i + 1])
            if m:
                out["totalRows"] = int(m.group(1).replace(",", ""))
        elif low.startswith("rows"):
            m = re.search(r"([\d,]+)", p)
            if m:
                out["totalRows"] = int(m.group(1).replace(",", ""))
        else:
            try:
                dt = datetime.strptime(p, "%B %d, %Y")
                out["analysisDate"] = dt.strftime("%Y-%m-%d")
                out["analysisDateLabel"] = p
            except ValueError:
                pass
    return out


def _parse_id(raw: str) -> dict:
    """Semantic-identity tuple: `glsub|00001|4230|P10` or `nz|00001|4240-4220`."""
    parts = [p.strip() for p in raw.split("|")] if raw else []
    out = {
        "issueType": parts[0] if len(parts) > 0 else None,
        "company":   parts[1] if len(parts) > 1 else None,
        "scope":     parts[2] if len(parts) > 2 else None,
        "glClass":   parts[3] if len(parts) > 3 else None,
    }
    # Two-tuple (unrec|4900) puts scope in [1], not company.
    if len(parts) == 2:
        out["company"] = None
        out["scope"] = parts[1]
    return out


def _read_analysis_sheet(ws) -> dict:
    """Walk the analyzer's Analysis sheet and emit `_meta` + worklists."""
    meta = {
        "title":         "",
        "subline":       "",
        "source":        "",
        "analysisDate":  "",
        "totalRows":     0,
        "flaggedCount":  0,
        "patternsCount": 0,
        "caveat":        "",
    }
    fix_first = []
    ask_customer = []
    ignore_blurb = ""

    # Locate landmark rows. Layout is fixed across runs (Analysis
    # sheet is generated by the analyzer), but be tolerant: search
    # by content rather than hard-coded row numbers.
    col1 = {r: _txt(ws.cell(r, 1).value) for r in range(1, ws.max_row + 1)}

    header_row = None
    for r, v in col1.items():
        if v and v.startswith("#") and "ID" in _txt(ws.cell(r, 2).value):
            header_row = r
            break

    # Title / subline / source strip / caveat: scan rows above the
    # table for known prefixes.
    for r, v in col1.items():
        if not v:
            continue
        if r == header_row:
            break
        if "Configuration Audit Worklist" in v or "DMAAI" in v and "—" in v and not meta["title"]:
            meta["title"] = v
        elif "F4095" in v and "flagged" in v and not meta["subline"]:
            meta["subline"] = v
            meta.update(_parse_subline(v))
        elif v.lower().startswith("source"):
            meta.update(_parse_source_strip(v))
        elif v.startswith("⚠") or v.startswith("⚠"):
            meta["caveat"] = re.sub(r"^[⚠⚠\s]+", "", v).strip()

    # Worklist rows: from header_row+1 until a blank row.
    if header_row:
        r = header_row + 1
        while r <= ws.max_row:
            n = _txt(ws.cell(r, 1).value)
            if not n:
                break
            sem = _parse_id(_txt(ws.cell(r, 2).value))
            row = {
                "id":         n,
                "issueType":  sem["issueType"],
                "company":    sem["company"],
                "scope":      sem["scope"],
                "glClass":    sem["glClass"],
                "module":     _txt(ws.cell(r, 4).value) or None,
                "task":       _txt(ws.cell(r, 6).value),
                "docTypes":   _txt(ws.cell(r, 7).value) or None,
                "glClasses":  _txt(ws.cell(r, 8).value) or None,
                "reference":  _txt(ws.cell(r, 9).value) or None,
            }
            kind = _txt(ws.cell(r, 3).value).lower()
            if kind.startswith("fix") or n.startswith("F"):
                fix_first.append(row)
            else:
                ask_customer.append(row)
            r += 1

    # IGNORE FOR NOW: row labeled "IGNORE FOR NOW" followed by the
    # explainer line(s). Treat the first non-empty non-header line
    # after that anchor as the blurb.
    anchor = None
    for r, v in col1.items():
        if v and v.upper().startswith("IGNORE FOR NOW"):
            anchor = r
            break
    if anchor:
        for r in range(anchor + 1, ws.max_row + 1):
            v = col1.get(r, "")
            if v:
                ignore_blurb = v
                break

    return {
        "_meta":        meta,
        "fixFirst":     fix_first,
        "askCustomer":  ask_customer,
        "ignoreBlurb":  ignore_blurb,
    }


def _read_jde_data_sheet(ws) -> dict:
    """Read JDE Data tab; bucket rows into module arrays + report any
    AAIs that don't fit a bucket. Headers in JDE Data carry trailing
    spaces (e.g. `Co `, `Sub `, `Or Ty`); normalize for lookup."""
    raw_hdr = [_txt(ws.cell(1, c).value) for c in range(1, ws.max_column + 1)]
    # Map source header -> canonical JSON key.
    canon = {
        "AAI Number":      "aaiNumber",
        "Co":              "companyNumber",
        "Or Ty":           "orderType",
        "Do Ty":           "docType",
        "G/L Cat":         "glClass",
        "Cost Type":       "costType",
        "Business Unit":   "businessUnit",
        "Obj Acct":        "objAccount",
        "Sub":             "subsidiary",
        "RR Analyzer Note": "analyzerNote",
    }
    idx = {}
    for c, h in enumerate(raw_hdr, start=1):
        key = canon.get(h.strip())
        if key:
            idx[key] = c

    modules: dict[str, list] = {m: [] for m in MODULE_AAI}
    unmapped: dict[str, int] = {}

    for r in range(2, ws.max_row + 1):
        aai = _txt(ws.cell(r, idx.get("aaiNumber", 1)).value)
        if not aai:
            continue
        target = None
        for module, tables in MODULE_AAI.items():
            if aai in tables:
                target = module
                break
        if target is None:
            unmapped[aai] = unmapped.get(aai, 0) + 1
            continue
        row = {}
        for key, c in idx.items():
            v = ws.cell(r, c).value
            row[key] = "" if v is None else str(v).strip()
        modules[target].append(row)

    return {
        "modules": modules,
        "unmappedAais": [
            {"aaiNumber": k, "rowCount": v}
            for k, v in sorted(unmapped.items())
        ],
    }


def extract(xlsx_path: Path) -> dict:
    wb = openpyxl.load_workbook(xlsx_path, data_only=True)
    if "Analysis" not in wb.sheetnames:
        raise SystemExit("Source workbook has no 'Analysis' sheet.")
    if "JDE Data" not in wb.sheetnames:
        raise SystemExit("Source workbook has no 'JDE Data' sheet.")

    analysis = _read_analysis_sheet(wb["Analysis"])
    jde = _read_jde_data_sheet(wb["JDE Data"])

    meta = analysis["_meta"]
    meta["runId"] = (
        (meta.get("analysisDate") or datetime.utcnow().strftime("%Y-%m-%d"))
        + "T00:00:00"
    )
    meta["unmappedAais"] = jde["unmappedAais"]

    return {
        "_meta":        meta,
        "fixFirst":     analysis["fixFirst"],
        "askCustomer":  analysis["askCustomer"],
        "ignoreBlurb":  analysis["ignoreBlurb"],
        "modules":      jde["modules"],
    }


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--xlsx",
        required=True,
        type=Path,
        help="Path to the analyzer's JDE DMAAIs Analysis {date}.xlsx",
    )
    ap.add_argument(
        "--out",
        type=Path,
        help="Output JSON path. Defaults to <repo>/RRV8/data/dmaai-analysis-latest.json",
    )
    args = ap.parse_args()

    if not args.xlsx.exists():
        raise SystemExit(f"Workbook not found: {args.xlsx}")

    out_path = args.out
    if out_path is None:
        # Resolve relative to this script: scripts/ -> ../data/
        out_path = Path(__file__).resolve().parent.parent / "data" / "dmaai-analysis-latest.json"

    payload = extract(args.xlsx)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(
        json.dumps(payload, indent=2, ensure_ascii=False),
        encoding="utf-8",
    )

    meta = payload["_meta"]
    print(
        f"Wrote {out_path} "
        f"({len(payload['fixFirst'])} fixFirst, "
        f"{len(payload['askCustomer'])} askCustomer, "
        f"{sum(len(v) for v in payload['modules'].values())} module rows, "
        f"{len(meta.get('unmappedAais', []))} unmapped AAIs)"
    )


if __name__ == "__main__":
    main()
