CREATE view         [dbo].[v6_006_unposted_cardex]             -- with encryption             as             select      periodends                                                          as PeriodEnds             ,           creationdate                
                                        as TransactionDate             ,           reportcompany                                                       as CompanyNumber             , case    when  a.ordernumber = 0 or a.doctype in ('OV','PV')      then 'Er
ror'    when        doctype in  (select * from  v6_common_mfgtypes) then 'Mfg'    when  doctype = 'IG' and a.ordertype like ('W%') then 'Mfg'             else        'Sales'             end                                                                  
           as Type             ,           isnull(a.ordertype, 'XX')                                           as OrderType             ,           longaccount                                                         as LongAccount             ,           
isnull(doctype,'')                                                  as DocType             ,           isnull(docnumber,0)                                                 as DocNumber             ,           branchplant                                    
                     as BranchPlant             ,case             when        doctype in  (select * from  v6_common_mfgtypes)             then        isnull(wasrst,'')             else        isnull(nextstatus,'')             end                          
                                                   as Status             ,           isnull(sum(amount),0)                                               as TransactionAmount             from (select reportcompany             ,           shortaccount      
       ,           branchplant             ,           periodends             ,           creationdate             , case when doctype in ('LC','LM') and ordertype = '' then 'LM' else ordertype end  as ordertype             ,           max(ordernumber)   
          as ordernumber             ,           doctype             ,           docnumber             ,           sum(amount) amount             from        rtransactions a             join        ritems b             on          a.itemid = b.itemid     
        where       batchnumber = 0              -- and         docnumber > 0  removed to display bad records             group by    reportcompany             ,           shortaccount             ,           branchplant             ,           periodends
    ,   creationdate             ,           ordertype             ,           doctype             ,           docnumber             having      round(sum(amount),2) != 0) a             join        rinvaccountlist c             on          a.shortaccount 
= c.shortaccount    and   a.reportcompany = c.companynumber             left join   f4801 d             on          ordertype = wadcto             and         ordernumber = wadoco             left join   (select sddcto                                     
                 as ordertype             ,           sddoco                                                              as ordernumber             ,           min(sdnxtr)                                                         as nextstatus             
from        vcr_f42119    where       sddoco > 0             group by    sddcto             ,           sddoco) e             on          a.ordertype = e.ordertype             and         a.ordernumber = e.ordernumber             group by    periodends   
          ,           creationdate             ,           reportcompany             ,           a.ordertype    ,   a.ordernumber             ,           longaccount             ,           doctype             ,           docnumber             ,          
 branchplant             ,           wasrst             ,           nextstatus
