CREATE view [dbo].[v_diagnostic5_job_status] as  select top 1 case run_status when 0 then 'Failed'          when 1 then 'Successful'          when 3 then 'Cancelled'          when 4 then 'In Progress'         when -1 then 'Not Found' end as JobStatus , co
nvert(varchar(20), job_date, 100)       as job_date , run_minutes             as [minutes] , isnull(avgminutes,0)           as [avg] , isnull(ct,0)             as [count]  from (   select top 100 percent   a.job_id            as job_id    , 4             
 as run_status   , getdate()            as job_date   , datediff(mi,start_execution_date, getdate())   as run_minutes   -- select *         from msdb.dbo.sysjobs j         , msdb.dbo.sysjobactivity a   ,(select job_id, max(run_requested_date) maxdate from
 msdb.dbo.sysjobactivity group by job_id) md         where a.job_id =j.job_id   and md.job_id = j.job_id         and j.name collate database_default= (select value from rsystemvariables where name = 'refreshjobname')         and a.run_requested_date is no
t null   and a.run_requested_date = md.maxdate         and a.stop_execution_date is null    union    select distinct top 100 percent   h.job_id                                     as job_id    , h.run_status                                    as run_statu
s   , cast(stuff(stuff(cast(h.run_date as varchar),7,0,'-'),5,0,'-') + ' ' + stuff(stuff(replace(str(h.run_time,6,0),' ','0'),5,0,':'),3,0,':') as datetime) as job_date   , ((run_duration/10000*3600 + (run_duration/100)%100*60 + run_duration%100 + 31 ) / 
60)                  as run_minutes   -- select *   from msdb..sysjobhistory h   ,  msdb..sysjobs j   where j.job_id = h.job_id   and  h.run_date =(select max(hi.run_date) from msdb..sysjobhistory hi where h.job_id = hi.job_id and step_name = '(Job outcom
e)')   and  h.run_time =(select max(hj.run_time) from msdb..sysjobhistory hj where h.job_id = hj.job_id and step_name = '(Job outcome)' and hj.run_date = (select max(hi.run_date) from msdb..sysjobhistory hi where h.job_id = hi.job_id and step_name = '(Job
 outcome)'))   and  j.name collate database_default= (select value from rsystemvariables where name = 'refreshjobname')   and  h.step_name = '(Job outcome)'    union    select top 100 percent null   as job_id    -- this section accounts for a job that has
 not been run yet   ,  -1        as run_status   ,  '1901-01-01'     as job_date   ,  0        as run_minutes    order by run_status desc   ) a  left join (                -- this section returns the average minutes and count for the last 10 job cycles   
select a.job_id, isnull(avg(a.run_duration),0) avgminutes, count(*) ct   from (select top 10 h.job_id, mx.run_duration   from msdb..sysjobhistory h   join msdb..sysjobs j   on  j.job_id = h.job_id   join  (select  job_id, run_date,((run_duration/10000*360
0 + (run_duration/100)%100*60 + run_duration%100 + 31 ) / 60) run_duration, max(run_time) run_time from msdb..sysjobhistory where run_status = '1' and step_name = '(Job outcome)' group by job_id, run_duration, run_date) mx   on  h.job_id = mx.job_id   and
  h.run_date = mx.run_date   and  h.run_time = mx.run_time   and  h.step_name = '(Job outcome)'    where j.name collate database_default= (select value from rsystemvariables where name = 'refreshjobname')   order by h.run_date desc) a   group by a.job_id 
  ) av   on  a.job_id = av.job_id  order by run_status desc
