------>>>>>>>>>>    UI Transaction Tab Procedures     CREATE Procedure    [dbo].[usp6getrcardexledgercompare]             ( @table                        nchar(30)                                       = null             , @companynumber                nv
archar(5)                                     = ''             , @accountnumber                nvarchar(28)                                    = ''             , @businessunit                 nvarchar(12)                                    = ''           
  , @periodends                   datetime                                        = null             , @excludecompanies             nvarchar(255)                                   = null             , @includecompanies             nvarchar(4000)         
                         = null             , @includebusinessunits         varchar     (max)                               = null             , @includeobjects               varchar     (max)        = null             , @includesubs                  varc
har     (max)        = null             , @withnotes                    bit                                             = 0             , @debug                        bit                                             = 0 )             -- with encryption   
          as             exec usp6getfilteredview             @table                                                                          = @table             , @companynumber                                                                = @companynu
mber             , @accountnumber                                                                = @accountnumber             , @businessunit                                                                 = @businessunit             , @periodends        
                                                           = @periodends             , @excludecompanies                                                             = @excludecompanies             , @includecompanies                                       
                      = @includecompanies             , @includebusinessunits                                                         = @includebusinessunits             , @includeobjects                                                               = @in
cludeobjects             , @includesubs                                                                  = @includesubs             , @viewname                                                                     = 'v6ui_reconcilingitems'             , @wi
thnotes                                                                    = @withnotes             , @debug                                                                        = @debug
