CREATE Procedure    [dbo].[usp6getbusinessunits]             ( @table                        nchar(30)                                       = null             , @companynumber                nvarchar(5)                                     = ''           
  , @accountnumber                nvarchar(28)                                    = ''             , @businessunit                 nvarchar(12)                                    = ''             , @periodends                   datetime                   
                     = null             , @excludecompanies             nvarchar(255)                                   = null             , @includecompanies             nvarchar(4000)                                  = null             , @includebusines
sunits         varchar     (max)                               = null             , @includeobjects               varchar     (max)        = null             , @includesubs                  varchar     (max)        = null             , @withnotes         
           bit                                             = 0             , @debug                        bit                                             = 0 )             -- with encryption             as             exec usp6getfilteredview            
 @table                                                                          = @table             , @companynumber                                                                = @companynumber             , @accountnumber                            
                                    = @accountnumber             , @businessunit                                                                 = @businessunit             , @periodends                                                                   = 
@periodends             , @excludecompanies                                                             = @excludecompanies             , @includecompanies                                                             = @includecompanies             , @incl
udebusinessunits                                                         = @includebusinessunits             , @includeobjects                                                               = @includeobjects             , @includesubs                      
                                            = @includesubs             , @viewname                                                                     = 'v6ui_getbusinessunits'             , @withnotes                                                      
              = @withnotes             , @debug                                                                        = @debug
