CREATE Procedure    [dbo].[usp6getinvpiedrilldown]             ( @companynumber                nvarchar(5)                                     = ''             , @accountnumber                nvarchar(28)                                    = ''           
  , @businessunit                 nvarchar(12)                                    = ''             , @periodends                   datetime                                        = null             , @excludecompanies             nvarchar(255)            
                       = null             , @includecompanies             nvarchar(4000)                                  = null             , @includebusinessunits         varchar     (max)                               = null             , @includeobjec
ts               varchar     (max)        = null             , @includesubs                  varchar     (max)        = null             , @useperiodendsle              bit                                             = 0             , @includecurrencies  
          nvarchar(512)                                   = null             , @pielevel                     tinyint                                         = 1             , @debug                        bit                                             = 
0 )             -- with encryption             as             -- pie levels             -- 1 = currencycode             -- 2 = company             -- 3 = business unit             -- 4 = object account             -- 5 = sub account             set nocoun
t on             -- *****************************************************************************************             declare     @sql                varchar(max)                                    = ''             declare     @where              varc
har (max)                                   = ''             declare     @peop               nvarchar (2)             -- *****************************************************************************************             set         @includebusinessunit
s = replace(@includebusinessunits, ' ','')             if          @useperiodendsle    = 0             begin       set @peop           = '='  end             else begin  set @peop           = '<=' end              if          @pielevel = 1             beg
in             set         @sql = '             select      Currency             ,           sum(oob) amount             from        v6ui_raccountsummary             '             goto        filteredwhere             end              if          @pieleve
l = 2             begin             set         @sql = '             select      companynumber             ,           sum(oob) amount             from        v6ui_raccountsummary             '             goto        filteredwhere             end        
      if          @pielevel = 3             begin             set         @sql = '             select      businessunit             ,           sum(oob) amount             from        v6ui_raccountsummary             '             goto        filteredwher
e             end              if          @pielevel = 4             begin             set         @sql = '             select      objectaccount             ,           sum(oob) amount             from        v6ui_raccountsummary             '           
  goto        filteredwhere             end              if          @pielevel = 5             begin             set         @sql = '             select      subaccount             ,           sum(oob) amount             from        v6ui_raccountsummary  
           '             goto        filteredwhere             end             -- filtered where clause             filteredwhere:             if          @periodends is not null             begin             if          len(@where) != 0 begin set @where 
= @where + ' and ' end             set         @where = @where + '  periodends ' + @peop + ' ''' + convert(nvarchar(30), @periodends, 101) + ''''             end             if @includecompanies is not null             begin             if          len(@w
here) != 0 begin set @where = @where + ' and ' end             set         @where = @where + '    companynumber in (' + @includecompanies + ')'             end             if          @includecurrencies is not null             begin             if        
  len(@where) != 0  begin set @where = @where + ' and ' end             set         @where = @where + '    currency in (' + @includecurrencies + ')'             end             if          @includebusinessunits is not null             begin             if
          len(@where) != 0  begin set @where = @where + ' and ' end             set         @where = @where + '  ltrim(businessunit) in (' + @includebusinessunits + ')'             end             if          @includeobjects is not null             begin 
            if          len(@where) != 0  begin set @where = @where + ' and ' end             set         @where = @where + '  objectaccount in (' + @includeobjects + ')' end             if          @includesubs is not null             begin             i
f          len(@where) != 0  begin set @where = @where + ' and ' end             set         @where = @where + '  rtrim(subaccount) in (' + @includesubs + ')' end             if          len(@where) > 0  begin set @sql = @sql + 'where ' + @where end      
       -- Group By             if          @pielevel = 1 begin set @sql = @sql + ' Group By Currency' end             if          @pielevel = 2 begin set @sql = @sql + ' Group By CompanyNumber' end             if          @pielevel = 3 begin set @sql = @s
ql + ' Group By BusinessUnit' end             if          @pielevel = 4 begin set @sql = @sql + ' Group By ObjectAccount' end             if          @pielevel = 5 begin set @sql = @sql + ' Group By SubAccount' end             -- *************************
****************************************************************             if       (@debug = 1) print isnull(@sql,'null query')             exec     (@sql)             set      nocount off
