CREATE Procedure    [dbo].[usp6getoutofbalance]             ( @companynumber                nvarchar(5)                                     = ''             , @accountnumber                nvarchar(28)                                    = ''             ,
 @businessunit                 nvarchar(12)                                    = ''             , @periodends                   datetime                                        = null             , @excludecompanies             nvarchar(255)               
                    = null             , @includecompanies             nvarchar(4000)                                   = null             , @includebusinessunits         varchar     (max)                               = null             , @includeobjects
               varchar     (max)        = null             , @includesubs                  varchar     (max)        = null             , @debug                        bit                                             = 0 )             -- with encryption    
         as             exec usp6getfilteredview             @companynumber                                                                  = @companynumber             , @accountnumber                                                                = @ac
countnumber             , @businessunit                                                                 = @businessunit             , @periodends                                                                   = @periodends             , @excludecompani
es                                                             = @excludecompanies             , @includecompanies                                                             = @includecompanies             , @includebusinessunits                         
                                = @includebusinessunits             , @includeobjects                                                               = @includeobjects             , @includesubs                                                               
   = @includesubs             , @viewname                                                                     = 'getoutofbalance'             , @debug                                                                        = 0
