CREATE Procedure    [dbo].[usp6getsubs]             ( @table                        nchar(30)                                       = null             , @companynumber                nvarchar(5)                                     = ''             , @acco
untnumber                nvarchar(28)                                    = ''             , @businessunit                 nvarchar(12)                                    = ''             , @periodends                   datetime                            
            = null             , @excludecompanies             nvarchar(255)                                   = null             , @includecompanies             nvarchar(4000)                                  = null             , @includebusinessunits   
      varchar     (max)                               = null             , @includeobjects               varchar     (max)        = null             , @includesubs                  varchar     (max)        = null             , @debug                      
  bit                                             = 0 )             -- with encryption             as             exec usp6getfilteredview             @table                                                                          = @table             , @
companynumber                                                                = @companynumber             , @accountnumber                                                                = @accountnumber             , @businessunit                         
                                        = @businessunit             , @periodends                                                                   = @periodends             , @excludecompanies                                                             =
 @excludecompanies             , @includecompanies                                                             = @includecompanies             , @includebusinessunits                                                         = @includebusinessunits         
    , @includeobjects                                                               = @includeobjects             , @includesubs                                                                  = @includesubs             , @viewname                       
                                              = 'v6ui_getsubs'             , @debug                                                                        = @debug
