CREATE Procedure    [dbo].[usp6getoutofbalancebysub]             ( @companynumber                nvarchar(5)                                     = ''             , @accountnumber                nvarchar(28)                                    = ''         
    , @businessunit                 nvarchar(12)                                    = ''             , @periodends                   datetime                                        = null             , @excludecompanies             nvarchar(255)          
                         = null             , @includecompanies             nvarchar(4000)                                  = null             , @includebusinessunits         varchar     (max)                               = null             , @includeobj
ects               varchar     (max)        = null             , @includesubs                  varchar     (max)        = null             , @debug                        bit                                             = 0 )             -- with encryption
             as             exec usp6getfilteredview             @companynumber                                                                  = @companynumber             , @accountnumber                                                                =
 @accountnumber             , @businessunit                                                                 = @businessunit             , @periodends                                                                   = @periodends             , @excludecom
panies                                                             = @excludecompanies             , @includecompanies                                                             = @includecompanies             , @includebusinessunits                     
                                    = @includebusinessunits             , @includeobjects                                                               = @includeobjects             , @includesubs                                                           
       = @includesubs             , @viewname                                                                     = 'v6ui_suggested_entry'             , @debug                                                                        = @debug
