CREATE Procedure    [dbo].[usp6getrinvaccountsummaryreports]             ( @companynumber                nvarchar(5)                                     = ''             , @accountnumber                nvarchar(28)                                    = '' 
            , @businessunit                 nvarchar(12)                                    = ''             , @periodends                   datetime                                        = null             , @excludecompanies             nvarchar(255)  
                                 = null             , @includecompanies             nvarchar(4000)                                  = null             , @includebusinessunits         varchar     (max)                               = null             , @in
cludeobjects               varchar     (max)        = null             , @includesubs                  varchar     (max)        = null             , @debug                        bit                                             = 0 )             -- with en
cryption             as             exec usp6getfilteredview             @companynumber                                                                  = @companynumber             , @accountnumber                                                         
       = @accountnumber             , @businessunit                                                                 = @businessunit             , @periodends                                                                   = @periodends             , @ex
cludecompanies                                                             = @excludecompanies             , @includecompanies                                                             = @includecompanies             , @includebusinessunits             
                                            = @includebusinessunits             , @includeobjects                                                               = @includeobjects             , @includesubs                                                   
               = @includesubs             , @viewname                                                                     = 'v6ui_accountsummaryreport'             , @debug                                                                        = @debug
