CREATE Procedure    [dbo].[usp6getaccounts]             ( @companynumber                nvarchar(5)                                     = ''             , @accountnumber                nvarchar(28)                                    = ''             , @bu
sinessunit                 nvarchar(12)                                    = ''             , @periodends                   datetime                                        = null             , @excludecompanies             nvarchar(255)                   
                = null             , @includecompanies             nvarchar(4000)                                  = null             , @includebusinessunits         varchar     (max)                               = null             , @includeobjects     
          varchar     (max)        = null             , @includesubs                  varchar     (max)        = null             , @debug                        bit                                             = 0 )             -- with encryption         
    as             exec usp6getfilteredview             @companynumber                                                                  = @companynumber             , @accountnumber                                                                = @account
number             , @businessunit                                                                 = @businessunit             , @periodends                                                                   = @periodends             , @excludecompanies   
                                                          = @excludecompanies             , @includecompanies                                                             = @includecompanies             , @includebusinessunits                              
                           = @includebusinessunits             , @includeobjects                                                               = @includeobjects             , @includesubs                                                                  = 
@includesubs             , @viewname                                                                     = 'v6ui_getaccounts'             , @debug                                                                        = @debug
