CREATE Procedure    [dbo].[usp6returnvalidationstatus]             ( @companynumber                nvarchar(5)                                     = ''             , @accountnumber                nvarchar(28)                                    = ''       
      , @businessunit                 nvarchar(12)                                    = ''             , @periodends                   datetime                                        = null             , @excludecompanies             nvarchar(255)        
                           = null             , @includecompanies             nvarchar(4000)                                  = null             , @includebusinessunits         varchar(max)                                    = null             , @includeo
bjects               varchar(max)         = null             , @includesubs                  varchar(max)         = null             , @debug                        bit                                             = 0 )             -- with encryption      
       as                 declare @sql varchar(max) = null    declare @where varchar(max) = ''     set         @sql =  'select isnull(max(status),0) as status         from         (select case when a.glrollok = ''No'' then 1         when a.oobrollok = ''N
o'' then 1        when a.GLRollOK = ''end'' and round(a.BeginningBalance,2) != round(c.EndingGLBalance,2) then 1        else 0 end as status         from raccountsummary a        join RAccountSummary c         -- added logic to check end period for status
 since the word no is not there         on a.CompanyNumber = c.CompanyNumber        and a.shortaccount = c.shortaccount         and c.PeriodEnds = dateadd(dd,-1,a.PeriodBegins)        join rinvaccountlist b         on a.longaccount = b.longaccount        
 where'                         if          @periodends is not null begin if len(@where) != 0 begin set @where = @where + '                          and'  end set @where = @where + '     a.periodends = ''' + convert(nvarchar(30), @periodends, 101) + '''' 
end                         if          @includecompanies is not null begin if len(@where) != 0  begin set @where = @where + '                          and '       end set @where = @where + '     b.companynumber in (' + @includecompanies + ')' end        
                 if          @includebusinessunits is not null and @includebusinessunits != '' begin if len(@where) != 0  begin set @where = @where + '                          and '       end set @where = @where + '     trimbu in (' + @includebusinessuni
ts + ')' end                         if          @includeobjects is not null and @includeobjects != '' begin if len(@where) != 0  begin set @where = @where + '                          and '       end set @where = @where + '     trimobj in (' + @includeob
jects + ')' end                         if          @includesubs is not null and @includesubs != '' begin if len(@where) != 0  begin set @where = @where + '                          and '       end set @where = @where + '     trimsub in (' + @includesubs 
+ ')' end                           set   @sql = @sql + @where + ')a'     if          (@debug = 1)        print isnull(@sql,'null query')                         exec        (@sql)
